repos:
- repo: local
  hooks:
  - id: eslint
    name: eslint-frontend
    entry: cd frontend && npm run style:linter
    files: frontend/
  - id: eslint
    name: eslint-backend
    entry: cd backend && npm run style:linter
    files: backend/
  - id: prettier
    name: prettier-frontend
    entry: cd frontend && npm run style:formatter
    files: frontend/
  - id: prettier
    name: prettier-backend
    entry: cd backend && npm run style:formatter
    files: backend/
